/**
 * Flights actions
 */
export const ADD_INBOUND_FLIGHT = 'ADD_INBOUND_FLIGHT'
export const ADD_OUTBOUND_FLIGHT = 'ADD_OUTBOUND_FLIGHT'
export const REMOVE_FLIGHTS = 'REMOVE_FLIGHTS'

export const ADD_FORM_ERRORS = 'ADD_FORM_ERRORS'
export const REMOVE_FORM_ERROR = 'REMOVE_FORM_ERROR'