/**
 * Flights actions
 */
export const ADD_INBOUND_FLIGHT = 'ADD_INBOUND_FLIGHT'
export const UPDATE_INBOUND_FLIGHT = 'UPDATE_INBOUND_FLIGHT'
export const REMOVE_INBOUND_FLIGHT = 'REMOVE_INBOUND_FLIGHT'

export const ADD_OUTBOUND_FLIGHT = 'ADD_OUTBOUND_FLIGHT'
export const UPDATE_OUTBOUND_FLIGHT = 'UPDATE_OUTBOUND_FLIGHT'
export const REMOVE_OUTBOUND_FLIGHT = 'REMOVE_OUTBOUND_FLIGHT'